import React from 'react'
import Head from 'next/head'
import CookieStandHeader from './Header'
import CookieStandForm from './Main'
import Footer from './Footer'
import { useState } from 'react'

function CookieStandAdmin(){
    const [located,setLocated] = useState('0')
    return (
        <div>
            <Head>
                 <title>Cookie Stand Admin</title>
                 <meta name="description" content="Generated by create next app" />
                 <link rel="icon" href="/favicon.ico" />
            </Head>  
    
            <CookieStandHeader/>
            
            <CookieStandForm setLocated={setLocated}/>
            <Footer located={located}/>
      </div>
    )
}
export default CookieStandAdmin